import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { Filter,Plus,Search } from 'lucide-react';
import { api,patch,post } from '../../core/api/client';
import type { Project,Task,User } from '../../core/api/types';
import { Badge,EmptyState,Modal,PageHeader,Spinner } from '../../core/components/ui';

const statuses=['backlog','todo','in_progress','blocked','in_review','completed','cancelled'];
export function TasksPage({forceCreate=0}:{forceCreate?:number}){
 const [tasks,setTasks]=useState<Task[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [members,setMembers]=useState<User[]>([]);const [loading,setLoading]=useState(true);const [modal,setModal]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [error,setError]=useState('');
 const load=useCallback(()=>{setLoading(true);const query=new URLSearchParams({limit:'100'});if(search)query.set('search',search);if(status)query.set('status',status);api<Task[]>(`/v1/tasks?${query}`).then(r=>setTasks(r.data)).finally(()=>setLoading(false));},[search,status]);
 useEffect(()=>{load()},[load]);useEffect(()=>{Promise.all([api<Project[]>('/v1/projects?limit=100'),api<User[]>('/v1/members')]).then(([p,m])=>{setProjects(p.data);setMembers(m.data)})},[]);useEffect(()=>{if(forceCreate)setModal(true)},[forceCreate]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const d=new FormData(e.currentTarget);try{await post('/v1/tasks',{title:d.get('title'),description:d.get('description'),projectId:d.get('projectId')||null,priority:d.get('priority'),dueAt:d.get('dueAt')?new Date(String(d.get('dueAt'))).toISOString():null,assigneeIds:d.getAll('assigneeIds')});setModal(false);load()}catch(err){setError(err instanceof Error?err.message:'Could not create task')}}
 async function changeStatus(task:Task,next:string){await patch(`/v1/tasks/${task.id}/status`,{status:next});setTasks(items=>items.map(item=>item.id===task.id?{...item,status:next,progress:next==='completed'?100:item.progress}:item));}
 return <><PageHeader eyebrow="Execution" title="Tasks" description="Plan, assign and move work from backlog to done." action={<button className="primary-button" onClick={()=>setModal(true)}><Plus size={18}/>Create task</button>}/><div className="toolbar"><label className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks…"/></label><label className="filter-select"><Filter size={17}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label></div><section className="table-card">{loading?<Spinner/>:tasks.length?<div className="data-table"><div className="table-head"><span>Task</span><span>Project</span><span>Priority</span><span>Status</span><span>Due date</span></div>{tasks.map(t=><div className="table-row" key={t.id}><div className="title-cell"><i className={`priority-bar ${t.priority}`}/><div><strong>{t.title}</strong><small>Task #{t.task_number}</small></div></div><span>{t.project_name||'—'}</span><Badge value={t.priority}/><select className="status-control" value={t.status} onChange={e=>changeStatus(t,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select><span className={t.due_at&&new Date(t.due_at)<new Date()&&t.status!=='completed'?'date overdue':'date'}>{t.due_at?new Date(t.due_at).toLocaleDateString():'No deadline'}</span></div>)}</div>:<EmptyState title="No tasks found" message="Create a task or change the current filters."/>}</section>{modal&&<Modal title="Create a new task" onClose={()=>setModal(false)}><form className="modal-form" onSubmit={create}><label>Task title<input name="title" placeholder="What needs to be done?" required autoFocus/></label><label>Description<textarea name="description" placeholder="Add useful context for the assignee" rows={4}/></label><div className="field-row"><label>Project<select name="projectId"><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Priority<select name="priority" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div><label>Due date<input name="dueAt" type="datetime-local"/></label><label>Assign to<select name="assigneeIds"><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name||m.name||m.email}</option>)}</select></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button">Create task</button></div></form></Modal>}</>;
}
