import { useState, type ReactNode } from 'react';
import { Bell, BookUser, BriefcaseBusiness, CheckSquare2, ChevronDown, LayoutDashboard, LogOut, Menu, Search, Settings, UsersRound, X } from 'lucide-react';
import { useAuth } from '../auth/AuthContext';

export type Section='dashboard'|'tasks'|'projects'|'contacts'|'teams'|'notifications';
const nav=[['dashboard','Overview',LayoutDashboard],['tasks','Tasks',CheckSquare2],['projects','Projects',BriefcaseBusiness],['contacts','Contacts',BookUser],['teams','Teams',UsersRound],['notifications','Notifications',Bell]] as const;
export function AppShell({section,onSection,children,unread=0}:{section:Section;onSection:(s:Section)=>void;children:ReactNode;unread?:number}){
 const {user,logout}=useAuth();const [open,setOpen]=useState(false);const select=(s:Section)=>{onSection(s);setOpen(false)};
 return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="sidebar-top"><div className="brand brand-light"><span className="brand-mark">W</span><span>workdeck</span></div><button className="sidebar-close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>select(id)}><Icon size={19}/><span>{label}</span>{id==='notifications'&&unread>0&&<b>{unread}</b>}</button>)}</nav><div className="sidebar-bottom"><button><Settings size={19}/><span>Workspace settings</span></button><div className="user-chip"><span>{(user?.full_name||user?.name||user?.email||'U').charAt(0).toUpperCase()}</span><div><strong>{user?.full_name||user?.name||'Workspace user'}</strong><small>{user?.role||'member'}</small></div><ChevronDown size={16}/></div><button className="logout" onClick={logout}><LogOut size={17}/> Sign out</button></div></aside><div className="mobile-overlay" onClick={()=>setOpen(false)}/><section className="workspace"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(true)}><Menu/></button><div className="global-search"><Search size={18}/><input placeholder="Search tasks, projects and people…"/></div><div className="top-actions"><button className="icon-button" onClick={()=>select('notifications')}><Bell size={20}/>{unread>0&&<i/>}</button><button className="profile-button"><span>{(user?.full_name||user?.name||user?.email||'U').charAt(0).toUpperCase()}</span><div><strong>{user?.full_name||user?.name||'My account'}</strong><small>{user?.role||'member'}</small></div></button></div></header><div className="page-content">{children}</div></section></div>;
}
