import { useEffect,useState } from 'react';
import { ArrowRight,BriefcaseBusiness,CalendarClock,CheckCircle2,CheckSquare2,Clock3,Plus,UsersRound } from 'lucide-react';
import { api } from '../../core/api/client';
import type { Project,Task } from '../../core/api/types';
import { Badge,PageHeader,Spinner } from '../../core/components/ui';

export function DashboardPage({onNewTask,onViewTasks}:{onNewTask:()=>void;onViewTasks:()=>void}){
 const [tasks,setTasks]=useState<Task[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([api<Task[]>('/v1/tasks?limit=100'),api<Project[]>('/v1/projects?limit=100')]).then(([t,p])=>{setTasks(t.data);setProjects(p.data)}).finally(()=>setLoading(false));},[]);
 if(loading)return <Spinner/>;const complete=tasks.filter(t=>t.status==='completed').length;const overdue=tasks.filter(t=>t.due_at&&new Date(t.due_at)<new Date()&&!['completed','cancelled'].includes(t.status)).length;const active=tasks.filter(t=>['todo','in_progress','blocked','in_review'].includes(t.status)).length;const rate=tasks.length?Math.round(complete/tasks.length*100):0;
 return <><PageHeader eyebrow="Workspace overview" title="Good work starts with clarity." description="See what is moving, what needs attention, and where your team should focus next." action={<button className="primary-button" onClick={onNewTask}><Plus size={18}/>New task</button>}/><section className="metric-grid"><Metric icon={<CheckSquare2/>} label="Active tasks" value={active} note={`${tasks.length} total tasks`}/><Metric icon={<BriefcaseBusiness/>} label="Active projects" value={projects.filter(p=>p.status==='active'||p.status==='planning').length} note={`${projects.length} across workspace`}/><Metric icon={<CalendarClock/>} label="Overdue" value={overdue} note={overdue?'Needs attention':'Everything on track'} alert={overdue>0}/><Metric icon={<CheckCircle2/>} label="Completion rate" value={`${rate}%`} note="Across all work"/></section><div className="dashboard-grid"><section className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">Priority queue</span><h2>Work that needs attention</h2></div><button className="text-button" onClick={onViewTasks}>View all <ArrowRight size={16}/></button></div><div className="task-rows">{tasks.slice(0,6).map(t=><div className="task-row" key={t.id}><span className={`priority-dot ${t.priority}`}/><div className="task-main"><strong>{t.title}</strong><small>{t.project_name||'No project'} · #{t.task_number}</small></div><Badge value={t.status}/><div className="due"><Clock3 size={15}/>{t.due_at?new Date(t.due_at).toLocaleDateString():'No deadline'}</div></div>)}{!tasks.length&&<div className="mini-empty">No tasks yet. Create your first task to get moving.</div>}</div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Portfolio</span><h2>Project progress</h2></div></div><div className="project-progress">{projects.slice(0,5).map(p=><div key={p.id}><div><strong>{p.name}</strong><span>{p.progress||0}%</span></div><div className="progress"><i style={{width:`${p.progress||0}%`}}/></div><small>{p.task_count||0} tasks · {p.status.replace('_',' ')}</small></div>)}{!projects.length&&<div className="mini-empty">Your projects will appear here.</div>}</div></section><section className="panel team-panel"><div className="panel-heading"><div><span className="eyebrow">Collaboration</span><h2>Team pulse</h2></div><UsersRound size={22}/></div><div className="pulse-number">{active}</div><p>tasks are currently moving through your team's workflow.</p><button className="secondary-button" onClick={onViewTasks}>Open task board</button></section></div></>;
}
function Metric({icon,label,value,note,alert=false}:{icon:React.ReactNode;label:string;value:string|number;note:string;alert?:boolean}){return <article className={alert?'metric alert':'metric'}><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>}
