import { useState, type FormEvent } from 'react';
import { ArrowRight, CheckCircle2, Layers3, ShieldCheck, Zap } from 'lucide-react';
import { useAuth } from './AuthContext';

export function AuthPage(){
  const {login,register}=useAuth(); const [mode,setMode]=useState<'login'|'register'>('login'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const email=String(data.get('email'));const password=String(data.get('password'));if(mode==='login')await login(email,password);else await register({name:String(data.get('name')),organizationName:String(data.get('organizationName')),email,password});}catch(err){setError(err instanceof Error?err.message:'Unable to continue');setBusy(false);}}
  return <main className="auth-shell"><section className="auth-story"><div className="brand brand-light"><span className="brand-mark">W</span><span>workdeck</span></div><div className="story-copy"><span className="eyebrow light">One place for serious work</span><h1>Turn plans into<br/><em>finished work.</em></h1><p>Projects, people and priorities stay aligned from the first assignment to the final update.</p><div className="story-points"><span><Zap/> Fast task workflows</span><span><ShieldCheck/> Secure tenant separation</span><span><Layers3/> Built to grow by modules</span></div></div><div className="story-foot"><span>Powered by Cloudflare</span><span>WhatsApp · SMS · Email</span></div></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand brand"><span className="brand-mark">W</span><span>workdeck</span></div><span className="eyebrow">Welcome to Workdeck</span><h2>{mode==='login'?'Sign in to your workspace':'Create your workspace'}</h2><p className="muted">{mode==='login'?'Keep your team moving forward.':'Set up your organization in under a minute.'}</p><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Register</button></div><form onSubmit={submit}>{mode==='register'&&<div className="field-row"><label>Full name<input name="name" placeholder="Jane Nansubuga" required/></label><label>Organization<input name="organizationName" placeholder="Acme Uganda" required/></label></div>}<label>Email address<input name="email" type="email" placeholder="you@company.com" required/></label><label>Password<input name="password" type="password" placeholder="Minimum 8 characters" minLength={8} required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button full" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create workspace'}<ArrowRight size={18}/></button></form><div className="auth-trust"><CheckCircle2 size={16}/> Your provider credentials remain securely on the backend.</div></div></section></main>;
}
